---
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - node_modules
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  project: './tsconfig.eslint.json'
rules:
  no-console:
    - error
  semi:
    - error
    - never
  quotes:
    - error
    - single
    - avoidEscape: true
